sudo: false
language: ruby
script: bundle exec script/test
cache: bundler

rvm:
  - 2.4.1

matrix:
  allow_failures:
    # "A fatal error has been detected by the Java Runtime Environment:
    #  Internal Error (sharedRuntime.cpp:843)"
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: jruby-20mode
    - rvm: jruby-21mode
    - rvm: jruby-head
    # random crashes
    - rvm: rbx-2
  fast_finish: true

env:
  matrix:
    - SSL=no
    - SSL=yes
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
